Repository HQ20/contracts, pull requests merged in 2019-12, with the labels that each got.

#16 Add Docs Website
  .travis.yml
  README.md
  netlify.toml
  package.json
  scripts/test.sh
  yarn.lock
Labels: enhancement

#58 New/whitelist
  contracts/drafts/access/README.md
  contracts/drafts/access/Whitelist.sol
  test/drafts/access/Whitelist.test.ts
Labels: new

#63 Fixed removeMember to onlyOwner.
  contracts/drafts/access/Whitelist.sol
Labels: bug
